In [142]:
#Python is both compile and interpreter language first it interpreter the code written and at the back
#compile the entire code

In [2]:
#How to use Git Sparse-Checkout command 
# git init
# git remote add -f origin [GIT URL]
# git config core.sparseCheckout true
# git sparse-checkout set [folder required]
# git pull from origin [branch name] // just for one time

In [2]:
#q2 To print the average of the numbers given in the list without using built in functions like max and len
a=0
b=0
l=[1,2,3,4,5,6]
for i in l:
    a=a+i # to find the sum like max
    b=b+1 # to find the count like len
    average=a/b
print('The average of the numbers given in the list',average)

The average of the numbers given in the list 3.5


In [1]:
#q1 to print max number in a list without using max in-built function
l=[1,2,3,4,5,6,4,5,6,100]
for i in l:
    num=l[0]
    if i>num:
        num=i
print(num)
print(max(l))

100
100


In [3]:
avg=(sum(l)/len(l))

In [4]:
avg

3.5

In [1]:
#Calendar
import calendar
   
for i in range(2011,2015,1):
    for j in range(1,13,1):
        print(calendar.month(i,j))

    January 2011
Mo Tu We Th Fr Sa Su
                1  2
 3  4  5  6  7  8  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30
31

   February 2011
Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6
 7  8  9 10 11 12 13
14 15 16 17 18 19 20
21 22 23 24 25 26 27
28

     March 2011
Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6
 7  8  9 10 11 12 13
14 15 16 17 18 19 20
21 22 23 24 25 26 27
28 29 30 31

     April 2011
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30

      May 2011
Mo Tu We Th Fr Sa Su
                   1
 2  3  4  5  6  7  8
 9 10 11 12 13 14 15
16 17 18 19 20 21 22
23 24 25 26 27 28 29
30 31

     June 2011
Mo Tu We Th Fr Sa Su
       1  2  3  4  5
 6  7  8  9 10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28 29 30

     July 2011
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30 31

    August 2011
Mo Tu We Th Fr

In [9]:
#commands to execute for plotly
!pip install cufflinks
!pip install plotly
import plotly as py
import plotly.express as px
from plotly.offline import iplot
import plotly.tools as tl
import cufflinks as cf

In [6]:
py.offline.init_notebook_mode(connected=True)
cf.go_offline()
import seaborn as sn
df=sn.load_dataset('iris')
df.iplot()

In [13]:
df.iplot(kind='hist',subplots=True)

In [15]:
df['sepal_length'].iplot(kind='hist')

In [ ]:
df.iplot()

In [7]:
#Ans:

class circle:
    def __init__(self,radius):#self is the pointer which can be reserved keyword, __init__ is the constructor
        self.radius=radius# __init__ help to pass the data to the circle and it also intialize the class circle
        
    def area(self):
        area=(3.14*self.radius**2)
        return area
        
class cylinder(circle):
    def __init__(self,radius,height):# radius, height are object variable or instance variable
        self.radius=radius
        self.height=height
        
    def area(self):#area is called the method of the class cylinder
        area = ((2*3.14*self.radius**2)+(2*3.14*self.radius*self.height))
        return area
    
    def volume(self):# volume is called the method of the class cylinder
        volume=(3.14*self.radius*2*self.height)
        return volume
        

In [8]:
cy=cylinder(2,50)# cy is the object of the class cylinder
cy.volume()# volume of the cylinder


628.0

In [9]:
cy.area()# area of the cylinder( here the methods area of the cylinder is overwridden by the area of the circle)

653.12

In [10]:
cr=circle(2) # cr is the object of the class circle
cr.area()# area of the circle 

12.56

In [11]:
#Ans
#1 Approach
a=1234
b=str(a)
l=[]
for i in b:
    l.append(i)
c=list(map(int,l))
sum1=0
for i in c:
    sum1+=i
print('the sum of the integers given are',sum1)

sum2=0
while(sum1>0):
    num=sum1%10
    sum2+=num
    sum1=sum1//10
print(sum2)
    

the sum of the integers given are 10
1


In [12]:
#Ans
#2 Approach
n=1234

add=0
while(n>0):
    last=n%10
    add+=last
    n=n//10
print('the sum of the numbers are',add)

sum2=0
while (add>0):
    last1=add%10
    sum2+=last1
    add=add//10
print(sum2)    



the sum of the numbers are 10
1


In [13]:
1234%10 # will get the last digit

4

In [14]:
1234/10 # division with the float number (means with decimal digits)

123.4

In [15]:
1234//10 # division with only decimal number ( means no decimal digits)

123

In [16]:
#Print the pair of the indexes which on addition gives the value of the target, along with their count and their index position

In [17]:
l=[20,70,40,20,50,60,10,30,80,90,10]
count=0
length=len(l)
target=80
for i in range(length):
    for j in range(1,length):
        if target==l[i]+l[j]:
            count += 1
            print([i,j])
print('the total number of pairs are',count)

[0, 5]
[1, 6]
[1, 10]
[2, 2]
[3, 5]
[4, 7]
[5, 3]
[6, 1]
[7, 4]
[10, 1]
the total number of pairs are 10


In [1]:
#write a pop function by your own

In [2]:
l=[1,23,4,5]
def pop_new(a):
    if type(a)==list:
        global l
        l=[ i for i in a[:len(l)-1:1]]
        return a
    else:
        print('there is some error')

In [3]:
pop_new([1,23,4,5])

[1, 23, 4, 5]

In [4]:
l

[1, 23, 4]

In [5]:
#write the code to reverse a string using for loop and while loop

In [8]:
s='zeeshan'
for i in range(len(s)-1,-1,-1):
    print(s[i],end='')

nahseez

In [11]:
s='zeeshan'
i=-1
last=len(s)

while -i<=last:
    print(s[i], end='')
    i=i-1

nahseez

In [ ]:
# write the code to filter the even number in a list using lambda function

In [13]:
l=[1,2,3,4,5,6,7,8,9,10]
n=lambda x:[i for i in x if i%2==0]
n(l)

[2, 4, 6, 8, 10]

In [15]:
[i for i in l if i%2==0]

[2, 4, 6, 8, 10]

In [22]:
def even(l):
    j=[]
    for i in l:
        if i%2==0:
            j.append(i)
    return j

In [23]:
even(l)

[2, 4, 6, 8, 10]

In [14]:
#write the code to print the prime numbers from 1 to 100 using lambda function

In [26]:
n=lambda x:[ i for i in range(100) if i%3==0]
n(5)

[0,
 3,
 6,
 9,
 12,
 15,
 18,
 21,
 24,
 27,
 30,
 33,
 36,
 39,
 42,
 45,
 48,
 51,
 54,
 57,
 60,
 63,
 66,
 69,
 72,
 75,
 78,
 81,
 84,
 87,
 90,
 93,
 96,
 99]

In [27]:
#write the code to print the prime square of number using lambda function

In [30]:
n=lambda x: [i*i for i in range(10)]
n(8)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

#write a lambda fuction which  takes multiple datatypes and give only strings

In [4]:
n=lambda *x:[i for i in x if type(i)==str]
n('df','zeeshan',25,5,[1,23,4,5],(1,23,4))

['df', 'zeeshan']

#write a lambda function to show the result whether even or odd


In [3]:
a=lambda x :'the number is even' if x%2==0 else 'the number is odd' 
print(a(20))
print(a(21))

the number is even
the number is odd


In [1]:
b=lambda x : 'the number is negative' if x<0 else 'the number is positive'
print(b(-1))
print(b(10))

the number is negative
the number is positive


In [11]:
x=['stue','kfjd',256,60,(20,30,40)]

In [31]:
x=('khan','sharrif',256,60,[20,30,40])

In [33]:
[i+' is a string' for i in x if type(i)==str ]

['khan is a string', 'sharrif is a string']

#dictionary can have only immutable elements as key ........and if we have duplicate keys in a dictionary the last is taken

In [2]:
d={'key':256,'key1':[1,2,3,4,5],'key':'checker'}

In [3]:
d['key']

'checker'

In [137]:
d # Here we have the duplicate key so the last part is taken into consideration

{'key': 'checker', 'key1': [1, 2, 3, 4, 5]}

In [138]:
#Dictionary keys will be only immutable entities like string and tuple int but not the list,set and dictionary itself

In [141]:
dd={'key':25,25:25,'string':265,(1,23,4):65,[1,2,3,4]:25,{"key":25}:36}#key cannot be list ,set and dictionary itself

TypeError: unhashable type: 'list'

In [148]:
def test():
    print('this is the Nonedatatype')

In [151]:
test()+'zeeshan'#You cannot add the None-type with the string

this is the Nonedatatype


TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

In [153]:
def test1(a):
    print(a)

In [158]:
type(test1(2))# this is the None type

2


NoneType

In [156]:
test1(2)+2 #Cannot add None type with the integer

2


TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [159]:
def test1(a):
    return a

In [161]:
test1(2)+2 #You can add the number 2 with the function since it is int datatype because you have used return statement

4

In [162]:
def test3(a,b,c,d):
    return a,b,c,d

In [164]:
test3(5,6,8,9)# datatype will be tuple if we pass multiple arguments

(5, 6, 8, 9)

In [165]:
type(test3(5,6,7,8))

tuple

In [166]:
def test4(*a):
    return a

In [168]:
test4(2)# the datatype will be tuple since we said that we will pass multiple arguments

(2,)

In [172]:
def test5(*a):#will pass every datatype but i need to get only list
    j=[]
    for i in a:
        if type(i)==list:
            j.append(i)
    return j

In [171]:
test5(2,3,4,5,6,'sudhd',[1,2,3,4,5])

[[1, 2, 3, 4, 5]]

In [175]:
def test6(*a):#will pass every datatype but i need to get only int in a list
    j=[]
    for i in a:
        if type(i)==int:
            j.append(i)
    return j

In [176]:
test6(1,2,3,4,5,6,[1,23,4,5],'sudh')

[1, 2, 3, 4, 5, 6]

In [177]:
def test7(*a,b):
    return a,b

In [179]:
test7(1,23,4,'dkfjkdf',b=8)#You have to specify the value of b separately the remaining will be considered as tuple 

((1, 23, 4, 'dkfjkdf'), 8)

In [184]:
test7(1,2,3,4,56)#Must specify b separately

TypeError: test7() missing 1 required keyword-only argument: 'b'

In [180]:
def test8(b,*a):
    return b,a

In [182]:
test8(1,23,4,5)# No need to specify b separately

(1, (23, 4, 5))

In [189]:
def test9(**b):#Must give the value in the form of key=25 .........
    return b

In [190]:
test9(key=25,key1=65,key2=[1,23,4])

{'key': 25, 'key1': 65, 'key2': [1, 23, 4]}

In [195]:
def test10(**c,*a):# You cannot specify keywords arguments at the begining 
    return c,a

SyntaxError: invalid syntax (2247217659.py, line 1)

In [6]:
def test10(*c,**a,d):# You cannot specify a arguments at the last 
    return c,a,d

SyntaxError: invalid syntax (474101230.py, line 1)

In [201]:
def test11(c,*d,**e):
    return c,d,e

In [202]:
test11(12,256,56,89,key=58)

(12, (256, 56, 89), {'key': 58})

In [5]:
def test123(*c,d,**e):#positional argument follows keyword argument

    return c,d,e

In [6]:
test123(12,256,d=56,key=58)

((12, 256), 56, {'key': 58})

# # Exception Handling

In [20]:
#there are two type of error ....
#1.Compile time error-syntax error(this will not handled by try and  except since there was syntax error )
#2.Run time error(this will be handled by try and except)
#try and except block will only handle run time error



In [23]:
print('this is the mistake'#this is the syntax error

SyntaxError: unexpected EOF while parsing (3798123116.py, line 1)

In [72]:
try:
    f=open('test.csv','r')
    f.write('iam writin into the file test')
    print('I have written in my test file')
except:
    print('this is my handler')#Except block will executed if there is error in the code written within the try block
else:
    print('this is my else block')#this will get executed if there is no error in the code written within the try block
finally:
    print('this is the finally block')#this will get executed all the time

this is my handler
this is the finally block


In [1]:
[i**3 for i in range(0,11)]

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [20]:
list(map(lambda x: x**3,range(10)))

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]

In [147]:
n=lambda x:[i**3 for i in range(10)]
n(8)

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]

In [29]:
f=open('test.csv','r')
f.write('this is the writing in test file')
print('this will get executed')
l=[1,2,33,4,5]
for i in l:
    print(i)

UnsupportedOperation: not writable

In [32]:
try:
    f=open('test.csv','r')
    f.write('this is the writing in test file')
    print('this will get executed')
except:
    print('this is the handler for file')
try:
    l=[1,2,33,4,5]
    for i in l:
        print(s[i])
except:
    print('this is my handler for list ')

this is the handler for file
this is my handler for list 


In [37]:
d={'key1':'sudh','key2':[1,23,4,5],'key3':(4,5,66,5)}
d['key4']=int(input())

dlkfj


ValueError: invalid literal for int() with base 10: 'dlkfj'

In [43]:
try:
    d={'key1':'sudh','key2':[1,23,4,5],'key3':(4,5,66,5)}
    d['key4']=int(input())
except Exception as e:#Exception word will handle all type of error
    print(e)

dlkj
invalid literal for int() with base 10: 'dlkj'


In [47]:
try:
    d={'key1':'sudh','key2':[1,23,4,5],'key3':(4,5,66,5)}
    d['key4']=int(input())
except ValueError as e:#It will only handle ValueError not any other errors
    print(e)

dfkjdl
invalid literal for int() with base 10: 'dfkjdl'


In [51]:
try:
    d={'key1':'sudh','key2':[1,23,4,5],'key3':(4,5,66,5)}
    d['key4']=int(input())
    f=open('test2','r')#it will not handle this error because only ValueError is called , but it will throw FileNotError
except ValueError as e:#It will only handle ValueError not any other errors
    print(e)

5545


FileNotFoundError: [Errno 2] No such file or directory: 'test2'

In [57]:
try:
    d={'key1':'sudh','key2':[1,23,4,5],'key3':(4,5,66,5)}
    d['key4']=int(input())
    f=open('test2','r')
except Exception as e:#it will  handle Multiple Error because Exception class is called
    print(e)

55
[Errno 2] No such file or directory: 'test2'


In [60]:
try:
    d={'key1':'sudh','key2':[1,23,4,5],'key3':(4,5,66,5)}
    d['key4']=int(input())
    f=open('test2','r')
except ValueError as e:#Calling each class at a time
    print(e)
except FileNotFoundError as e:#Calling filenotfoundError class
    print(e)

55
[Errno 2] No such file or directory: 'test2'


In [15]:
try:
    d={'key1':'sudh','key2':[1,23,4,5],'key3':(4,5,66,5)}
    d['key4']=int(input())
    c=int(input())
    a=88/c

except ZeroDivisionError as e:#the first mentioned class will be called following the hierarchy
    print(e)
except FileNotFoundError as e:
    print(e)
except Exception as e:#Ultimately Exception class will handle this error by following the hiereachy from the top
    print('this  is my exception class',e)

55
0
division by zero


In [10]:
d

{'key1': 'sudh', 'key2': [1, 23, 4, 5], 'key3': (4, 5, 66, 5), 'key4': 55}

In [11]:
try:
    d={'key1':'sudh','key2':[1,23,4,5],'key3':(4,5,66,5)}
    d['key4']=int(input())
    c=int(input())
    a=88/c
except Exception as e:#the first mentioned class will be called it won't go below since it is a superclass
    print('this  is my exception class',e)
except ValueError as e:#division by zero is not mentioned but it is handling because of Exception given at the top
    print(e)
except FileNotFoundError as e:
    print(e)


0
0
this  is my exception class division by zero


In [79]:
try:
    d={'key1':'sudh','key2':[1,23,4,5],'key3':(4,5,66,5)}
    d['key4']=int(input())
    c=int(input())
    a=88/c

except FileNotFoundError as e:
    print(e)
except ValueError as e:#ValueError is mentioned at the second position but it handled
    print(e)

jhj
invalid literal for int() with base 10: 'jhj'


In [3]:
def enter_int1():#Calling the try except block inside a fuction
    try:
        a=int(input())
        return a
    except Exception as e:
        print(e)

In [4]:
enter_int1()

dkfj
invalid literal for int() with base 10: 'dkfj'


In [3]:
#You have to enter the input unless until the input is integer again and agian
def enter_int():

        while True:
            try:
                a=int(input())
                print('this is the correct input ',a)
                break
            except:
                print('Enter the input as integer')

In [ ]:
enter_int()

jdhf
Enter the input as integer
jdhf
Enter the input as integer
dhf
Enter the input as integer


In [25]:

#You have to enter the input unless until the input is dictionary again and again
while True:
        try:
            a=eval(input())
            print('this is the correct input',a)
            break
        except:
            print('Please give the correct input ')

kjfd
Please give the correct input 
dkjfd
Please give the correct input 
dkfj
Please give the correct input 
5
this is the correct input 5


In [34]:
#creating your own custom message
def test(a):
    if type(a)==int:
        raise Exception ('you are not suppose to give int as input',a)#Own custome Exception
    return a

In [35]:
test([1,23,4])

[1, 23, 4]

In [36]:
test(2)

Exception: ('you are not suppose to give int as input', 2)

In [8]:
#creating your own custom message by overriding the systems message
try:
    d={'key1':'sudh','key2':[1,23,4,5],'key3':(4,5,66,5)}
    d['key4']=int(input())#two error you can see here one is value error and one is your own custom message 
    f=open('test2','r')#My own custom message
except:
    raise Exception('there is no file found with test2 name')

lkkahf


Exception: there is no file found with test2 name

# Pandas

In [6]:
df=pd.DataFrame(np.random.rand(10,6),index=pd.date_range('2021-05-20',periods=10),columns=['a','b','c','d','e','f'])


In [7]:
df

a         b         c         d         e         f
2021-05-20  0.501960  0.871418  0.896076  0.792122  0.482616  0.496585
2021-05-21  0.236683  0.983952  0.580205  0.872571  0.353156  0.866261
2021-05-22  0.218719  0.816218  0.732690  0.219276  0.659985  0.643124
2021-05-23  0.966307  0.002224  0.377073  0.862146  0.259353  0.646741
2021-05-24  0.719199  0.737938  0.749671  0.271741  0.326732  0.945160
2021-05-25  0.836325  0.175179  0.562783  0.727068  0.901610  0.931503
2021-05-26  0.730000  0.488072  0.899355  0.377866  0.880558  0.485665
2021-05-27  0.144702  0.333246  0.409992  0.846648  0.947828  0.507585
2021-05-28  0.556578  0.810359  0.535235  0.176242  0.045081  0.534973
2021-05-29  0.827223  0.464193  0.989342  0.331316  0.898449  0.167392

In [8]:
df.index # to call the index 

DatetimeIndex(['2021-05-20', '2021-05-21', '2021-05-22', '2021-05-23',
               '2021-05-24', '2021-05-25', '2021-05-26', '2021-05-27',
               '2021-05-28', '2021-05-29'],
              dtype='datetime64[ns]', freq='D')

In [105]:
df.columns

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [106]:
type(df['a'])

pandas.core.series.Series

In [107]:
df.describe()

a          b          c          d          e          f
count  10.000000  10.000000  10.000000  10.000000  10.000000  10.000000
mean    0.573770   0.568280   0.673242   0.547700   0.575537   0.622499
std     0.290986   0.326767   0.212654   0.295026   0.325015   0.240969
min     0.144702   0.002224   0.377073   0.176242   0.045081   0.167392
25%     0.303002   0.365982   0.542122   0.286635   0.333338   0.499335
50%     0.637888   0.613005   0.656448   0.552467   0.571300   0.589049
75%     0.802917   0.814753   0.859475   0.833016   0.893977   0.811381
max     0.966307   0.983952   0.989342   0.872571   0.947828   0.945160

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 10 entries, 2021-05-20 to 2021-05-29
Freq: D
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       10 non-null     float64
 1   b       10 non-null     float64
 2   c       10 non-null     float64
 3   d       10 non-null     float64
 4   e       10 non-null     float64
 5   f       10 non-null     float64
dtypes: float64(6)
memory usage: 860.0 bytes


In [110]:
df.dtypes[df.dtypes =='float'].index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [111]:
df.to_json() # to display the dataframe directly to json format

'{"a":{"1621468800000":0.5019599662,"1621555200000":0.2366826886,"1621641600000":0.2187193647,"1621728000000":0.9663073729,"1621814400000":0.7191989551,"1621900800000":0.8363246515,"1621987200000":0.7300001212,"1622073600000":0.1447016034,"1622160000000":0.5565778985,"1622246400000":0.8272232553},"b":{"1621468800000":0.8714184665,"1621555200000":0.983952207,"1621641600000":0.8162175654,"1621728000000":0.0022235221,"1621814400000":0.7379375621,"1621900800000":0.1751793901,"1621987200000":0.4880724387,"1622073600000":0.3332457413,"1622160000000":0.8103588165,"1622246400000":0.4641926409},"c":{"1621468800000":0.8960756636,"1621555200000":0.5802053027,"1621641600000":0.7326898644,"1621728000000":0.3770731248,"1621814400000":0.7496711978,"1621900800000":0.5627832668,"1621987200000":0.8993549581,"1622073600000":0.4099917446,"1622160000000":0.5352347904,"1622246400000":0.9893422987},"d":{"1621468800000":0.792122415,"1621555200000":0.8725708129,"1621641600000":0.2192757142,"1621728000000":0.86

In [112]:
type(df.to_json())

str

In [114]:
converted=eval(df.to_json()) # converted string to json format or dictionary to make it a dataframe since string isn't supported

In [115]:
converted


{'a': {'1621468800000': 0.5019599662,
  '1621555200000': 0.2366826886,
  '1621641600000': 0.2187193647,
  '1621728000000': 0.9663073729,
  '1621814400000': 0.7191989551,
  '1621900800000': 0.8363246515,
  '1621987200000': 0.7300001212,
  '1622073600000': 0.1447016034,
  '1622160000000': 0.5565778985,
  '1622246400000': 0.8272232553},
 'b': {'1621468800000': 0.8714184665,
  '1621555200000': 0.983952207,
  '1621641600000': 0.8162175654,
  '1621728000000': 0.0022235221,
  '1621814400000': 0.7379375621,
  '1621900800000': 0.1751793901,
  '1621987200000': 0.4880724387,
  '1622073600000': 0.3332457413,
  '1622160000000': 0.8103588165,
  '1622246400000': 0.4641926409},
 'c': {'1621468800000': 0.8960756636,
  '1621555200000': 0.5802053027,
  '1621641600000': 0.7326898644,
  '1621728000000': 0.3770731248,
  '1621814400000': 0.7496711978,
  '1621900800000': 0.5627832668,
  '1621987200000': 0.8993549581,
  '1622073600000': 0.4099917446,
  '1622160000000': 0.5352347904,
  '1622246400000': 0.989342

In [116]:
type(converted)

dict

In [117]:
pd.DataFrame(converted)

a         b         c         d         e         f
1621468800000  0.501960  0.871418  0.896076  0.792122  0.482616  0.496585
1621555200000  0.236683  0.983952  0.580205  0.872571  0.353156  0.866261
1621641600000  0.218719  0.816218  0.732690  0.219276  0.659985  0.643124
1621728000000  0.966307  0.002224  0.377073  0.862146  0.259353  0.646741
1621814400000  0.719199  0.737938  0.749671  0.271741  0.326732  0.945160
1621900800000  0.836325  0.175179  0.562783  0.727068  0.901610  0.931503
1621987200000  0.730000  0.488072  0.899355  0.377866  0.880558  0.485665
1622073600000  0.144702  0.333246  0.409992  0.846648  0.947828  0.507585
1622160000000  0.556578  0.810359  0.535235  0.176242  0.045081  0.534973
1622246400000  0.827223  0.464193  0.989342  0.331316  0.898449  0.167392

In [118]:
df.to_json('test')#to store the dataframe in the local system

In [119]:
f=open('test','r')# to open the file test 
type(f.read()) #the datatype will be string by default if you open in f.read() mode
s=f.read()

In [120]:
#To convert the string into json we can follow two methods
#1. Using eval function
#2. Using json.loads()

#1. Using eval function
f=open('test','r') 
s=f.read()

In [121]:
#1.Using eval function
s

'{"a":{"1621468800000":0.5019599662,"1621555200000":0.2366826886,"1621641600000":0.2187193647,"1621728000000":0.9663073729,"1621814400000":0.7191989551,"1621900800000":0.8363246515,"1621987200000":0.7300001212,"1622073600000":0.1447016034,"1622160000000":0.5565778985,"1622246400000":0.8272232553},"b":{"1621468800000":0.8714184665,"1621555200000":0.983952207,"1621641600000":0.8162175654,"1621728000000":0.0022235221,"1621814400000":0.7379375621,"1621900800000":0.1751793901,"1621987200000":0.4880724387,"1622073600000":0.3332457413,"1622160000000":0.8103588165,"1622246400000":0.4641926409},"c":{"1621468800000":0.8960756636,"1621555200000":0.5802053027,"1621641600000":0.7326898644,"1621728000000":0.3770731248,"1621814400000":0.7496711978,"1621900800000":0.5627832668,"1621987200000":0.8993549581,"1622073600000":0.4099917446,"1622160000000":0.5352347904,"1622246400000":0.9893422987},"d":{"1621468800000":0.792122415,"1621555200000":0.8725708129,"1621641600000":0.2192757142,"1621728000000":0.86

In [122]:
type(s)

str

In [123]:
dat=eval(s)

In [140]:
type(dat)

dict

In [141]:
dat


{'a': {'1621468800000': 0.5019599662,
  '1621555200000': 0.2366826886,
  '1621641600000': 0.2187193647,
  '1621728000000': 0.9663073729,
  '1621814400000': 0.7191989551,
  '1621900800000': 0.8363246515,
  '1621987200000': 0.7300001212,
  '1622073600000': 0.1447016034,
  '1622160000000': 0.5565778985,
  '1622246400000': 0.8272232553},
 'b': {'1621468800000': 0.8714184665,
  '1621555200000': 0.983952207,
  '1621641600000': 0.8162175654,
  '1621728000000': 0.0022235221,
  '1621814400000': 0.7379375621,
  '1621900800000': 0.1751793901,
  '1621987200000': 0.4880724387,
  '1622073600000': 0.3332457413,
  '1622160000000': 0.8103588165,
  '1622246400000': 0.4641926409},
 'c': {'1621468800000': 0.8960756636,
  '1621555200000': 0.5802053027,
  '1621641600000': 0.7326898644,
  '1621728000000': 0.3770731248,
  '1621814400000': 0.7496711978,
  '1621900800000': 0.5627832668,
  '1621987200000': 0.8993549581,
  '1622073600000': 0.4099917446,
  '1622160000000': 0.5352347904,
  '1622246400000': 0.989342

In [142]:
#2.Using json.loads()
import json
converted=json.loads(s)# converted the string to json or dictionary 

In [143]:
converted

{'a': {'1621468800000': 0.5019599662,
  '1621555200000': 0.2366826886,
  '1621641600000': 0.2187193647,
  '1621728000000': 0.9663073729,
  '1621814400000': 0.7191989551,
  '1621900800000': 0.8363246515,
  '1621987200000': 0.7300001212,
  '1622073600000': 0.1447016034,
  '1622160000000': 0.5565778985,
  '1622246400000': 0.8272232553},
 'b': {'1621468800000': 0.8714184665,
  '1621555200000': 0.983952207,
  '1621641600000': 0.8162175654,
  '1621728000000': 0.0022235221,
  '1621814400000': 0.7379375621,
  '1621900800000': 0.1751793901,
  '1621987200000': 0.4880724387,
  '1622073600000': 0.3332457413,
  '1622160000000': 0.8103588165,
  '1622246400000': 0.4641926409},
 'c': {'1621468800000': 0.8960756636,
  '1621555200000': 0.5802053027,
  '1621641600000': 0.7326898644,
  '1621728000000': 0.3770731248,
  '1621814400000': 0.7496711978,
  '1621900800000': 0.5627832668,
  '1621987200000': 0.8993549581,
  '1622073600000': 0.4099917446,
  '1622160000000': 0.5352347904,
  '1622246400000': 0.989342

In [144]:
type(converted)

dict

In [145]:
pd.DataFrame(converted)

a         b         c         d         e         f
1621468800000  0.501960  0.871418  0.896076  0.792122  0.482616  0.496585
1621555200000  0.236683  0.983952  0.580205  0.872571  0.353156  0.866261
1621641600000  0.218719  0.816218  0.732690  0.219276  0.659985  0.643124
1621728000000  0.966307  0.002224  0.377073  0.862146  0.259353  0.646741
1621814400000  0.719199  0.737938  0.749671  0.271741  0.326732  0.945160
1621900800000  0.836325  0.175179  0.562783  0.727068  0.901610  0.931503
1621987200000  0.730000  0.488072  0.899355  0.377866  0.880558  0.485665
1622073600000  0.144702  0.333246  0.409992  0.846648  0.947828  0.507585
1622160000000  0.556578  0.810359  0.535235  0.176242  0.045081  0.534973
1622246400000  0.827223  0.464193  0.989342  0.331316  0.898449  0.167392

In [146]:
import requests # to pull the raw data from json format from website

In [147]:
data=requests.get('https://gist.githubusercontent.com/ski7777/04d63680373f11e32a98adc11928cf7e/raw/f0d4b026cffe4d2c15ecf05a36473bb9f5d81aab/raw.json')

In [148]:
h=data.json()

In [149]:
h

{'appName': {'Microsoft Internet Explorer': 1, 'Netscape': 837},
 'appVersion': {'4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.0)': 1,
  '5.0 (Android)': 3,
  '5.0 (Linux; Android 6.0.1; GT-I9195 Build/MOB30D) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2718.2 Mobile Safari/537.36': 10,
  '5.0 (Linux; Android 6.0.1; GT-I9195 Build/MOB30D) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2723.0 Mobile Safari/537.36': 10,
  '5.0 (Linux; Android 6.0.1; GT-I9195 Build/MOB30D) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2739.3 Mobile Safari/537.36': 5,
  '5.0 (Linux; Android 6.0.1; GT-I9195 Build/MOB30D) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.8 Mobile Safari/537.36': 3,
  '5.0 (Linux; Android 6.0.1; GT-I9195 Build/MOB30J) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.8 Mobile Safari/537.36': 1,
  '5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36': 4,
  '5.0 (Windows NT 10.0; WOW64; Trident/7.0; 

In [150]:
type(h)

dict

In [151]:
pd.DataFrame(h)# to insert the data in Dataframe the datatype should be dictionary or json

appName  appVersion  \
Microsoft Internet Explorer                             1.0         NaN   
Netscape                                              837.0         NaN   
4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trid...      NaN         1.0   
5.0 (Android)                                           NaN         3.0   
5.0 (Linux; Android 6.0.1; GT-I9195 Build/MOB30...      NaN        10.0   
...                                                     ...         ...   
Sat                                                     NaN         NaN   
Sun                                                     NaN         NaN   
Thu                                                     NaN         NaN   
Tue                                                     NaN         NaN   
Wed                                                     NaN         NaN   

                                                    appCodeName  platform  \
Microsoft Internet Explorer                                 NaN       NaN   
Netscape                                                    NaN       NaN   
4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trid...          NaN       NaN   
5.0 (Android)                                               NaN       NaN   
5.0 (Linux; Android 6.0.1; GT-I9195 Build/MOB30...          NaN       NaN   
...                                                         ...       ...   
Sat                                                         NaN       NaN   
Sun                                                         NaN       NaN   
Thu                                                         NaN       NaN   
Tue                                                         NaN       NaN   
Wed                                                         NaN       NaN   

                                                    lang  userAgent  Java  \
Microsoft Internet Explorer                          NaN        NaN   NaN   
Netscape                                             NaN        NaN   NaN   
4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trid...   NaN        NaN   NaN   
5.0 (Android)                                        NaN        NaN   NaN   
5.0 (Linux; Android 6.0.1; GT-I9195 Build/MOB30...   NaN        NaN   NaN   
...                                                  ...        ...   ...   
Sat                                                  NaN        NaN   NaN   
Sun                                                  NaN        NaN   NaN   
Thu                                                  NaN        NaN   NaN   
Tue                                                  NaN        NaN   NaN   
Wed                                                  NaN        NaN   NaN   

                                                    CoresCPU  windowHeight  \
Microsoft Internet Explorer                              NaN           NaN   
Netscape                                                 NaN           NaN   
4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trid...       NaN           NaN   
5.0 (Android)                                            NaN           NaN   
5.0 (Linux; Android 6.0.1; GT-I9195 Build/MOB30...       NaN           NaN   
...                                                      ...           ...   
Sat                                                      NaN           NaN   
Sun                                                      NaN           NaN   
Thu                                                      NaN           NaN   
Tue                                                      NaN           NaN   
Wed                                                      NaN           NaN   

                                                    windowWidth  maxHeight  \
Microsoft Internet Explorer                                 NaN        NaN   
Netscape                                                    NaN        NaN   
4.0 (compatible; MSIE 7.0; Windows NT 5.1; Trid...          NaN        NaN   
5.0 (Android)                                       

In [1]:
import seaborn as sn    

In [4]:
df1=sn.load_dataset('iris')

In [5]:
df1

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [9]:
df2=df1.to_json(orient='records')#to remove the indexes we must give orient as records

In [10]:
type(df2)

str

In [133]:
import json
df3=json.loads(df2)# this is the right record which can be dumbed into mongodb

In [14]:
df3

[{'sepal_length': 5.1,
  'sepal_width': 3.5,
  'petal_length': 1.4,
  'petal_width': 0.2,
  'species': 'setosa'},
 {'sepal_length': 4.9,
  'sepal_width': 3.0,
  'petal_length': 1.4,
  'petal_width': 0.2,
  'species': 'setosa'},
 {'sepal_length': 4.7,
  'sepal_width': 3.2,
  'petal_length': 1.3,
  'petal_width': 0.2,
  'species': 'setosa'},
 {'sepal_length': 4.6,
  'sepal_width': 3.1,
  'petal_length': 1.5,
  'petal_width': 0.2,
  'species': 'setosa'},
 {'sepal_length': 5.0,
  'sepal_width': 3.6,
  'petal_length': 1.4,
  'petal_width': 0.2,
  'species': 'setosa'},
 {'sepal_length': 5.4,
  'sepal_width': 3.9,
  'petal_length': 1.7,
  'petal_width': 0.4,
  'species': 'setosa'},
 {'sepal_length': 4.6,
  'sepal_width': 3.4,
  'petal_length': 1.4,
  'petal_width': 0.3,
  'species': 'setosa'},
 {'sepal_length': 5.0,
  'sepal_width': 3.4,
  'petal_length': 1.5,
  'petal_width': 0.2,
  'species': 'setosa'},
 {'sepal_length': 4.4,
  'sepal_width': 2.9,
  'petal_length': 1.4,
  'petal_width': 0.2

In [17]:
len(df3)

150

In [18]:
type(df3)

list

In [24]:
col=list(df3[0].keys())

In [22]:
list(df3[0].values())

[5.1, 3.5, 1.4, 0.2, 'setosa']

In [26]:
#creating new dataframe to dump the data one by one
import pandas as pd
df4=pd.DataFrame(columns=col)

In [27]:
df4

Empty DataFrame
Columns: [sepal_length, sepal_width, petal_length, petal_width, species]
Index: []

In [28]:
df4.loc[0]=df3[0].values()

In [29]:
df4

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa

In [31]:
for i in range(len(df3)):
    df4.loc[i]=df3[i].values()

In [33]:
df4

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [1]:
import pandas as pd

In [64]:
d3=[
    {
        'empid':35,
        'lastname':'zeeshan',
        'firstname':'khan'
    },
     {
        'empid':450,
        'lastname':'Faizan',
        'firstname':'khan'
    }, {
        'empid':3585,
        'lastname':'Javed',
        'firstname':'khan'
    }, {
        'empid':3578,
        'lastname':'mukesh',
        'firstname':'khan'
    }, {
        'empid':355,
        'lastname':'patthan',
        'firstname':'khan'
    }
    
]

In [65]:
df3=pd.DataFrame(d3)
df4=pd.DataFrame(d3)

In [28]:
df=pd.DataFrame(d)

In [29]:
d1 =[
    {
        'empid1':54,
        'lastname1':'Arvind',
        'firstname1':'kumarr'
    },
     {
        'empid1':885,
        'lastname1':'bharat',
        'firstname1':'khanan'
    }, {
        'empid1':88,
        'lastname1':'sudhasnshu',
        'firstname1':'kumar'
    }, {
        'empid1':87,
        'lastname1':'Nethtu',
        'firstname1':'singh'
    }, {
        'empid1':45,
        'lastname1':'paresh',
        'firstname1':'patil'
    }
    
]

In [30]:
df1=pd.DataFrame(d1)

In [31]:
df

empid lastname firstname
0     35  zeeshan      khan
1    450   Faizan      khan
2   3585    Javed      khan
3   3578   mukesh      khan
4    355  patthan      khan

In [32]:
df1

empid1   lastname1 firstname1
0      54      Arvind     kumarr
1     885      bharat     khanan
2      88  sudhasnshu      kumar
3      87      Nethtu      singh
4      45      paresh      patil

In [106]:
pd.concat([df,df],axis=1)#vertical joining axis=1,horizontal joining axis =0

empid lastname firstname  empid lastname firstname
0     35  zeeshan      khan     35  zeeshan      khan
1    450   Faizan      khan    450   Faizan      khan
2   3585    Javed      khan   3585    Javed      khan
3   3578   mukesh      khan   3578   mukesh      khan
4    355  patthan      khan    355  patthan      khan

In [36]:
df

empid lastname firstname
0     35  zeeshan      khan
1    450   Faizan      khan
2   3585    Javed      khan
3   3578   mukesh      khan
4    355  patthan      khan

In [37]:
df1

empid1   lastname1 firstname1
0      54      Arvind     kumarr
1     885      bharat     khanan
2      88  sudhasnshu      kumar
3      87      Nethtu      singh
4      45      paresh      patil

In [107]:
pd.merge(df,df1,left_on='empid',right_on='empid1',how='left')
#if common column is not available but we have common data then 
#we use lefton and righton

empid lastname firstname  empid1 lastname1 firstname1
0     35  zeeshan      khan     NaN       NaN        NaN
1    450   Faizan      khan     NaN       NaN        NaN
2   3585    Javed      khan     NaN       NaN        NaN
3   3578   mukesh      khan     NaN       NaN        NaN
4    355  patthan      khan     NaN       NaN        NaN

In [105]:
pd.merge(df3,df4,on='empid',how='left')#merge helps to join the common columns

empid lastname_x firstname_x lastname_y firstname_y
0     35    zeeshan        khan    zeeshan        khan
1    450     Faizan        khan     Faizan        khan
2   3585      Javed        khan      Javed        khan
3   3578     mukesh        khan     mukesh        khan
4    355    patthan        khan    patthan        khan

In [75]:
data=[
    {
        'empid':35,
        'lastname':'zeeshan',
        'firstname':'khan'
    },
     {
        'empid':450,
        'lastname':'Faizan',
        'firstname':'khan'
    }, {
        'empid':3585,
        'lastname':'Javed',
        'firstname':'khan'
    }, {
        'empid':3578,
        'lastname':'mukesh',
        'firstname':'khan'
    }
    
]

In [76]:
data

[{'empid': 35, 'lastname': 'zeeshan', 'firstname': 'khan'},
 {'empid': 450, 'lastname': 'Faizan', 'firstname': 'khan'},
 {'empid': 3585, 'lastname': 'Javed', 'firstname': 'khan'},
 {'empid': 3578, 'lastname': 'mukesh', 'firstname': 'khan'}]

In [92]:
data1=[
    {
        'empid1':35,
        'lastname1':'zeeshan',
        'firstname1':'khan'
    },
     {
        'empid1':450,
        'lastname1':'Faizan',
        'firstname1':'khan'
    }, {
        'empid1':3585,
        'lastname1':'Javed',
        'firstname1':'khan'
    }
]

In [93]:
df5=pd.DataFrame(data,index=['a','b','c','d'])
df6=pd.DataFrame(data1,index=['a','b','c'])


In [94]:
df5

empid lastname firstname
a     35  zeeshan      khan
b    450   Faizan      khan
c   3585    Javed      khan
d   3578   mukesh      khan

In [95]:
df6

empid1 lastname1 firstname1
a      35   zeeshan       khan
b     450    Faizan       khan
c    3585     Javed       khan

In [108]:
df5.join(df6,how='right')#join helps to join the index but the column name should be different

empid lastname firstname  empid1 lastname1 firstname1
a     35  zeeshan      khan      35   zeeshan       khan
b    450   Faizan      khan     450    Faizan       khan
c   3585    Javed      khan    3585     Javed       khan

In [1]:
import pandas as pd
a=pd.ExcelFile('LUSID Excel - Manage Orders.xlsx')
l=[]
for i in a.sheet_names:
    l.append(pd.read_excel('LUSID Excel - Manage Orders.xlsx',sheet_name=i))

In [4]:
pd.concat([l[0],l[1],l[2],l[3],l[4]],axis=1)#combining multiple sheet into single sheet

Unnamed: 0                                   Unnamed: 1  \
0          NaN  This sheet allows you to manage executions:   
1          NaN                           1. List executions   
2          NaN                             2. Get execution   
3          NaN                         3. Upsert executions   
4          NaN                                          NaN   
..         ...                                          ...   
66         NaN                                          NaN   
67         NaN                                          NaN   
68         NaN                                          NaN   
69         NaN                                          NaN   
70         NaN                                          NaN   

           Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7  \
0                 NaN        NaN        NaN        NaN        NaN        NaN   
1                 NaN        NaN        NaN        NaN        NaN        NaN   
2                 NaN        NaN        NaN        NaN        NaN        NaN   
3                 NaN        NaN        NaN        NaN        NaN        NaN   
4                 NaN        NaN        NaN        NaN        NaN        NaN   
..                ...        ...        ...        ...        ...        ...   
66                NaN        NaN        NaN        NaN        NaN        NaN   
67                NaN        NaN        NaN        NaN        NaN        NaN   
68               Code        NaN        NaN        NaN        NaN        NaN   
69  MyExecutionCode01        NaN        NaN        NaN        NaN        NaN   
70                NaN        NaN        NaN        NaN        NaN        NaN   

   Unnamed: 8 Unnamed: 9  ... Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10  \
0         NaN        NaN  ...        NaN        NaN        NaN         NaN   
1         NaN        NaN  ...        NaN        NaN        NaN         NaN   
2         NaN        NaN  ...        NaN        NaN        NaN         NaN   
3         NaN        NaN  ...        NaN        NaN        NaN         NaN   
4         NaN        NaN  ...        NaN        NaN        NaN         NaN   
..        ...        ...  ...        ...        ...        ...         ...   
66        NaN        NaN  ...        NaN        NaN        NaN         NaN   
67        NaN        NaN  ...        NaN        NaN        NaN         NaN   
68        NaN        NaN  ...        NaN        NaN        NaN         NaN   
69        NaN        NaN  ...        NaN        NaN        NaN         NaN   
70        NaN        NaN  ...        NaN        NaN        NaN         NaN   

   Unnamed: 11 Unnamed: 12 Unnamed: 13 Unnamed: 14 Unnamed: 15  Unnamed: 16  
0          NaN         NaN         NaN         NaN         NaN          NaN  
1          NaN         NaN         NaN         NaN         NaN          NaN  
2          NaN         NaN         NaN         NaN         NaN          NaN  
3          NaN         NaN         NaN         NaN         NaN          NaN  
4          NaN         NaN         NaN         NaN         NaN          NaN  
..         ...         ...         ...         ...         ...          ...  
66         NaN         NaN         NaN         NaN         NaN          NaN  
67         NaN         NaN         NaN         NaN         NaN          NaN  
68         NaN         NaN         NaN         NaN         NaN          NaN  
69         NaN         NaN         NaN         NaN         NaN          NaN  
70         NaN         NaN         NaN         NaN         NaN          NaN  

[71 rows x 100 columns]

# Numpy

In [40]:
import numpy as np

In [41]:
l=[1,2,3,4,5]

In [42]:
a=np.array(l)#convert list to array

In [43]:
a#single dimension array is same as the list

array([1, 2, 3, 4, 5])

In [49]:
type(a)

numpy.ndarray

In [50]:
l

[1, 2, 3, 4, 5]

In [51]:
np.array(l,ndmin=2)#two brackets means two dimensional array

array([[1, 2, 3, 4, 5]])

In [52]:
np.array(l,ndmin=3)#three brackets means three dimensional array

array([[[1, 2, 3, 4, 5]]])

In [53]:
np.array(l)#default it's the single dimensional array

array([1, 2, 3, 4, 5])

In [54]:
np.arange(5,15,0.2)#In numpy we can give float value in the arange function

array([ 5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,  7. ,
        7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,  9.2,
        9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4,
       11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6,
       13.8, 14. , 14.2, 14.4, 14.6, 14.8])

In [55]:
list(range(5,15,0.2))#we cannot give float value in normal range function

TypeError: 'float' object cannot be interpreted as an integer

In [56]:
b=np.arange(2,15,0.2)

In [57]:
b#it is like a list

array([ 2. ,  2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,
        4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,
        6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,
        8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6,
       10.8, 11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8,
       13. , 13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8])

In [58]:
b[0]#we can call the value using range fuction since it is a list

2.0

In [59]:
np.asanyarray(l)#same as np.array

array([1, 2, 3, 4, 5])

In [60]:
np.asarray(l)#samee as np.array, it is similiar to a list

array([1, 2, 3, 4, 5])

In [61]:
np.mat(a)#default matrix will be two dimensional array

matrix([[1, 2, 3, 4, 5]])

In [62]:
np.random.randint(25)#it give a value less than 25 randomly everytime when executed

12

In [63]:
np.random.randn(4,5)#we will get the value in 4 rows and 5 column whose avg is zero and Normal distribution is 1

array([[-0.10909941,  0.66252449, -0.26235442,  0.41035791,  0.09153492],
       [ 1.95288617,  0.26922307, -0.11737193,  1.10353721, -0.13768597],
       [-0.32817372,  1.1296909 , -2.14881765,  0.01077729,  0.10180592],
       [-1.48191169, -1.51410661, -0.46179441,  0.42179181, -0.92762639]])

In [64]:
np.random.rand(4,5)#it just give the value in 4 rows and 5 column

array([[0.57626325, 0.68957466, 0.52160458, 0.13499721, 0.38142983],
       [0.96744943, 0.23537389, 0.69539391, 0.00604415, 0.91126536],
       [0.1477984 , 0.22720176, 0.64174329, 0.09764936, 0.87511941],
       [0.89725682, 0.28554246, 0.98228028, 0.73355649, 0.27048147]])

In [65]:
x=np.arange(20)#this is single dimensional array

In [66]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [67]:
x.size#20 elements are there in this list or array 

20

In [68]:
x.reshape(4,-1)# Here -1 will automatically calculated  5 column , the result what we want is 4*5=20

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [69]:
y=x.reshape(4,5)# we will define the value 4*5=20

In [70]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [71]:
import pandas as pd
pd.DataFrame(y)


0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [72]:
l=np.array([1,2,3,4,5],ndmin=1)

In [73]:
l#list or single dimensional array

array([1, 2, 3, 4, 5])

In [74]:
pd.DataFrame(l)#if the array is one dimension we can call pandas

0
0  1
1  2
2  3
3  4
4  5

In [75]:
l=np.array([1,2,3,4,5],ndmin=2)

In [76]:
l#two dimension  since two brackets

array([[1, 2, 3, 4, 5]])

In [77]:
l=np.array([1,2,3,4,5],ndmin=3)

In [78]:
l# Here the array is three dimensional

array([[[1, 2, 3, 4, 5]]])

In [79]:
pd.DataFrame(l)#We cannot insert the data into the pandas dataframe since it is three dimensional (three brackets)

ValueError: Must pass 2-d input. shape=(1, 1, 5)

In [80]:
np.fromfunction(lambda x,y,z :x*y*z,(2,3,4))#here 4 is column 3 is rows and 2 is the no of such values

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 1., 2., 3.],
        [0., 2., 4., 6.]]])

In [81]:
a = np.fromfunction(lambda y,z :y*z,(3,2))#here 2 is column 3 is rows

In [82]:
a

array([[0., 0.],
       [0., 1.],
       [0., 2.]])

In [83]:
np.fromfunction(lambda x,y,Z : x*y*Z ,(4,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 1.]],

       [[0., 0.],
        [0., 2.]],

       [[0., 0.],
        [0., 3.]]])

In [84]:
np.array([[1,2],[3,4]])#two dimensional array

array([[1, 2],
       [3, 4]])

In [87]:
np.ones(10) #It gives 10 values which are 1 and returns floating point number by default

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [88]:
np.zeros(10)#It gives 10 values which are 0 and returns floating point number

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [89]:
np.ones((4,5))#It give 4 rows and 5 columns which are having value 1.0 #default the datatype is float

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [90]:
np.zeros((4,5))#It give 4 rows and 5 columns which are having value 0.0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [91]:
5+np.ones((4,5)) #5 is add to each and every element which is called broadcasting

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [92]:
np.random.rand(4,5).reshape(5,-1)

array([[0.47482609, 0.99227605, 0.36266438, 0.0800726 ],
       [0.25652414, 0.18899573, 0.65858066, 0.10820552],
       [0.02788285, 0.36153727, 0.37807576, 0.69848004],
       [0.12260624, 0.26312161, 0.82517623, 0.74984194],
       [0.67990671, 0.3023736 , 0.79973809, 0.69903858]])

In [93]:
x=np.arange(20).reshape(5,4)

In [94]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [95]:
pow(x,2)#it square every value

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361]], dtype=int32)

In [96]:
pow(x,3)#it cubes every value

array([[   0,    1,    8,   27],
       [  64,  125,  216,  343],
       [ 512,  729, 1000, 1331],
       [1728, 2197, 2744, 3375],
       [4096, 4913, 5832, 6859]], dtype=int32)

In [97]:
a=np.arange(12).reshape(4,3)

In [98]:
b=np.arange(12).reshape(4,3)

In [99]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [103]:
b[0]

0

In [104]:
b

array([0, 1, 2])

In [105]:
a*b#it only multiplies the number directly

array([[ 0,  1,  4],
       [ 0,  4, 10],
       [ 0,  7, 16],
       [ 0, 10, 22]])

In [106]:
a@b#this is the actually multiplication of the matrix like a*b

array([ 5, 14, 23, 32])

In [107]:
np.linspace(2,10,100)#it print the value between 2 and 10, 100 is the number of the value

array([ 2.        ,  2.08080808,  2.16161616,  2.24242424,  2.32323232,
        2.4040404 ,  2.48484848,  2.56565657,  2.64646465,  2.72727273,
        2.80808081,  2.88888889,  2.96969697,  3.05050505,  3.13131313,
        3.21212121,  3.29292929,  3.37373737,  3.45454545,  3.53535354,
        3.61616162,  3.6969697 ,  3.77777778,  3.85858586,  3.93939394,
        4.02020202,  4.1010101 ,  4.18181818,  4.26262626,  4.34343434,
        4.42424242,  4.50505051,  4.58585859,  4.66666667,  4.74747475,
        4.82828283,  4.90909091,  4.98989899,  5.07070707,  5.15151515,
        5.23232323,  5.31313131,  5.39393939,  5.47474747,  5.55555556,
        5.63636364,  5.71717172,  5.7979798 ,  5.87878788,  5.95959596,
        6.04040404,  6.12121212,  6.2020202 ,  6.28282828,  6.36363636,
        6.44444444,  6.52525253,  6.60606061,  6.68686869,  6.76767677,
        6.84848485,  6.92929293,  7.01010101,  7.09090909,  7.17171717,
        7.25252525,  7.33333333,  7.41414141,  7.49494949,  7.57

In [108]:
np.linspace(2,3,45,dtype=float,endpoint=False)#It will not print the upper bound value


array([2.        , 2.02222222, 2.04444444, 2.06666667, 2.08888889,
       2.11111111, 2.13333333, 2.15555556, 2.17777778, 2.2       ,
       2.22222222, 2.24444444, 2.26666667, 2.28888889, 2.31111111,
       2.33333333, 2.35555556, 2.37777778, 2.4       , 2.42222222,
       2.44444444, 2.46666667, 2.48888889, 2.51111111, 2.53333333,
       2.55555556, 2.57777778, 2.6       , 2.62222222, 2.64444444,
       2.66666667, 2.68888889, 2.71111111, 2.73333333, 2.75555556,
       2.77777778, 2.8       , 2.82222222, 2.84444444, 2.86666667,
       2.88888889, 2.91111111, 2.93333333, 2.95555556, 2.97777778])

In [109]:
values=np.linspace(20,100,50).reshape(10,-1)

In [110]:
values

array([[ 20.        ,  21.63265306,  23.26530612,  24.89795918,
         26.53061224],
       [ 28.16326531,  29.79591837,  31.42857143,  33.06122449,
         34.69387755],
       [ 36.32653061,  37.95918367,  39.59183673,  41.2244898 ,
         42.85714286],
       [ 44.48979592,  46.12244898,  47.75510204,  49.3877551 ,
         51.02040816],
       [ 52.65306122,  54.28571429,  55.91836735,  57.55102041,
         59.18367347],
       [ 60.81632653,  62.44897959,  64.08163265,  65.71428571,
         67.34693878],
       [ 68.97959184,  70.6122449 ,  72.24489796,  73.87755102,
         75.51020408],
       [ 77.14285714,  78.7755102 ,  80.40816327,  82.04081633,
         83.67346939],
       [ 85.30612245,  86.93877551,  88.57142857,  90.20408163,
         91.83673469],
       [ 93.46938776,  95.10204082,  96.73469388,  98.36734694,
        100.        ]])

In [111]:
pd.DataFrame(values)

0          1          2          3           4
0  20.000000  21.632653  23.265306  24.897959   26.530612
1  28.163265  29.795918  31.428571  33.061224   34.693878
2  36.326531  37.959184  39.591837  41.224490   42.857143
3  44.489796  46.122449  47.755102  49.387755   51.020408
4  52.653061  54.285714  55.918367  57.551020   59.183673
5  60.816327  62.448980  64.081633  65.714286   67.346939
6  68.979592  70.612245  72.244898  73.877551   75.510204
7  77.142857  78.775510  80.408163  82.040816   83.673469
8  85.306122  86.938776  88.571429  90.204082   91.836735
9  93.469388  95.102041  96.734694  98.367347  100.000000

In [112]:
values1=np.logspace(3,4,49).reshape(7,-1)

In [113]:
values1

array([[ 1000.        ,  1049.13972914,  1100.69417125,  1154.78198469,
         1211.52765863,  1271.06179961,  1333.52143216],
       [ 1399.05031414,  1467.79926762,  1539.92652606,  1615.59809844,
         1694.98815139,  1778.27941004,  1865.66357858],
       [ 1957.34178149,  2053.52502646,  2154.43469003,  2260.30302714,
         2371.37370566,  2487.90236724,  2610.15721568],
       [ 2738.41963426,  2872.98483335,  3014.16252988,  3162.27766017,
         3317.67112784,  3480.70058843,  3651.74127255],
       [ 3831.18684956,  4019.45033362,  4216.96503429,  4424.18555385,
         4641.58883361,  4869.67525166,  5108.96977451],
       [ 5360.02316539,  5623.4132519 ,  5899.74625592,  6189.65818891,
         6493.81631576,  6812.92069058,  7147.70576794],
       [ 7498.94209332,  7867.4380766 ,  8254.04185268,  8659.6432336 ,
         9085.17575652,  9531.61883235, 10000.        ]])

In [114]:
pd.DataFrame(values1)

0            1            2            3            4  \
0  1000.000000  1049.139729  1100.694171  1154.781985  1211.527659   
1  1399.050314  1467.799268  1539.926526  1615.598098  1694.988151   
2  1957.341781  2053.525026  2154.434690  2260.303027  2371.373706   
3  2738.419634  2872.984833  3014.162530  3162.277660  3317.671128   
4  3831.186850  4019.450334  4216.965034  4424.185554  4641.588834   
5  5360.023165  5623.413252  5899.746256  6189.658189  6493.816316   
6  7498.942093  7867.438077  8254.041853  8659.643234  9085.175757   

             5             6  
0  1271.061800   1333.521432  
1  1778.279410   1865.663579  
2  2487.902367   2610.157216  
3  3480.700588   3651.741273  
4  4869.675252   5108.969775  
5  6812.920691   7147.705768  
6  9531.618832  10000.000000

In [115]:
np.empty((4,5))

array([[0.47482609, 0.99227605, 0.36266438, 0.0800726 , 0.25652414],
       [0.18899573, 0.65858066, 0.10820552, 0.02788285, 0.36153727],
       [0.37807576, 0.69848004, 0.12260624, 0.26312161, 0.82517623],
       [0.74984194, 0.67990671, 0.3023736 , 0.79973809, 0.69903858]])

In [116]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [117]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])

In [118]:
a.max()

11

In [119]:
b=a.T

In [120]:
b

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [121]:
b.max(axis=0)#It  take the row views starting from 0,1,2 and so on

array([ 2,  5,  8, 11])

In [122]:
b.max(axis=1)#It takes the colums views starting from o,3,6,9 and so on

array([ 9, 10, 11])

In [126]:
a=np.arange(20).reshape(4,-5)

In [127]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [129]:
b=a.T

In [131]:
b#Transpose of the matrix

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [132]:
b.max(axis=0)

array([ 4,  9, 14, 19])

# Mysql

In [50]:
import pandas as pd
import mysql.connector as cn
mydb=cn.connect(host='localhost',user='root',passwd='snzk@#1329')
cursor=mydb.cursor()
#cursor.execute('show databases')
cursor.execute('use dress_data')
cursor.execute('show tables')
#cursor.execute('select * from dress1')
cursor.fetchall()
#mydb.commit()

[('dress',),
 ('dress1',),
 ('test2',),
 ('test3',),
 ('test4',),
 ('test65',),
 ('test66',),
 ('test67',)]

In [54]:
pd.read_sql('select * from dress_data.dress1',mydb)# to connect with pandas and mysql  syntax database.table name

Dress_ID  New_dress_id    Style    Price Size Season NeckLine  \
0    1006032852    1006032852     Sexy      Low  4.6      M   Summer   
1    1212192089    1212192089   Casual      Low    0      L   Summer   
2    1190380701    1190380701  vintage     High    0      L   Automn   
3     966005983     966005983    Brief  Average  4.6      L   Spring   
4     876339541     876339541     cute      Low  4.5      M   Summer   
..          ...           ...      ...      ...  ...    ...      ...   
495   713391965     713391965   Casual      Low  4.7      M   Spring   
496   722565148     722565148     Sexy      Low  4.3   free   Summer   
497   532874347     532874347   Casual  Average  4.7      M   Summer   
498   655464934     655464934   Casual  Average  4.6      L   winter   
499   919930954     919930954   Casual      Low  4.4   free   Summer   

    SleeveLength  waiseline Material     FabricType  Decoration Pattern Type  \
0         o-neck  sleevless   empire           null     chiffon      ruffles   
1         o-neck      Petal  natural     microfiber        null      ruffles   
2         o-neck       full  natural       polyster        null         null   
3         o-neck       full  natural           silk     chiffon   embroidary   
4         o-neck  butterfly  natural  chiffonfabric     chiffon          bow   
..           ...        ...      ...            ...         ...          ...   
495       o-neck       full  natural       polyster        null         null   
496       o-neck       full   empire         cotton        null         null   
497       v-neck       full   empire         cotton        null         lace   
498    boat-neck  sleevless   empire           silk  broadcloth     applique   
499       v-neck      short   empire         cotton    Corduroy         lace   

    Recommendation  
0           animal  
1           animal  
2            print  
3            print  
4              dot  
..             ...  
495          solid  
496           null  
497          solid  
498          print  
499          solid  

[500 rows x 14 columns]

In [56]:
pd.read_sql_query('select * from dress1',mydb) #if you are using the database then give table name only

C:\Users\91986\anaconda3\lib\site-packages\pandas\io\sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(


Dress_ID  New_dress_id    Style    Price Size Season NeckLine  \
0    1006032852    1006032852     Sexy      Low  4.6      M   Summer   
1    1212192089    1212192089   Casual      Low    0      L   Summer   
2    1190380701    1190380701  vintage     High    0      L   Automn   
3     966005983     966005983    Brief  Average  4.6      L   Spring   
4     876339541     876339541     cute      Low  4.5      M   Summer   
..          ...           ...      ...      ...  ...    ...      ...   
495   713391965     713391965   Casual      Low  4.7      M   Spring   
496   722565148     722565148     Sexy      Low  4.3   free   Summer   
497   532874347     532874347   Casual  Average  4.7      M   Summer   
498   655464934     655464934   Casual  Average  4.6      L   winter   
499   919930954     919930954   Casual      Low  4.4   free   Summer   

    SleeveLength  waiseline Material     FabricType  Decoration Pattern Type  \
0         o-neck  sleevless   empire           null     chiffon      ruffles   
1         o-neck      Petal  natural     microfiber        null      ruffles   
2         o-neck       full  natural       polyster        null         null   
3         o-neck       full  natural           silk     chiffon   embroidary   
4         o-neck  butterfly  natural  chiffonfabric     chiffon          bow   
..           ...        ...      ...            ...         ...          ...   
495       o-neck       full  natural       polyster        null         null   
496       o-neck       full   empire         cotton        null         null   
497       v-neck       full   empire         cotton        null         lace   
498    boat-neck  sleevless   empire           silk  broadcloth     applique   
499       v-neck      short   empire         cotton    Corduroy         lace   

    Recommendation  
0           animal  
1           animal  
2            print  
3            print  
4              dot  
..             ...  
495          solid  
496           null  
497          solid  
498          print  
499          solid  

[500 rows x 14 columns]

In [58]:
pd.read_sql('select * from mysql.gtid_executed',mydb)

Empty DataFrame
Columns: [source_uuid, interval_start, interval_end]
Index: []

# Flask

In [74]:
!pip install flask
import requests
!pip install json
from flask import Flask , jsonify



ERROR: Could not find a version that satisfies the requirement json (from versions: none)
ERROR: No matching distribution found for json


# Oops

In [18]:
class xyz:
    def __init__(self,a,b,c):
        self.a=a
        self.b=b
        self.c=c
        
    def test1(self):
        return self.a
    
    def test2(self):
        return self.test1()+self.b
    
class abc(xyz):
    def __init__(self,p,q,r,*args):
        super(abc,self).__init__(*args)
        self.p=p
        self.q=q
        self.r=r
        
    def test3(self):
        return self.a
    
    def test4(self):
        return self.a+self.b

In [20]:
ob=abc(10,20,30,40,50,60)

In [21]:
ob.a


40

In [23]:
class xyz:
    def __init__(self,a,b,c):
        self.a=a
        self.b=b
        self.c=c
        
    def test1(self):
        return self.a
    
    def test2(self):
        return self.test1()+self.b
    
class abc:
    def __init__(self,p,q,r):
        self.p=p
        self.q=q
        self.r=r
        
    def test3(self):
        return self.a
    
    def test4(self):
        return self.a+self.b

In [33]:
class ddd(abc,xyz):
    def __init__(self,h,*args,**kwargs):
        self.h=h
        abc.__init__(self,*args)
        xyz.__init__(self,**kwargs)

In [35]:
ob=ddd(40,50,60,80,a=400,b=600,c=700)

In [38]:
ob.test4()

1000

In [1]:
class check(str):#Calling the methods and instance variable of the inbuilt class
    def __init__(self,*args):

        super(check,self).__init__(*args)

In [41]:
ob=check()

In [42]:
ob.capitalize()

''

In [45]:
class check(str):#Calling the methods and instance variable of the inbuilt function
    def __init__(self,*args):
        str.__init__(self,*args)

In [47]:
ob=check()

In [48]:
ob.capitalize()

''

In [78]:
class car:
    __var='help'
    _var='no help'
    var='superb'
    def __init__(self,a,b,c):
        self.a=a
        self._b=b
        self.__c=c
       
    @staticmethod
    def __test():
        print('this is the test method',car._var)
        
class dog(car):
    def __init__(self,p,q,r,*args):
        self.p=p
        self.q=q
        self.r=r
        super(dog,self).__init__(*args)
        
    def test1(self):
        print('this is the test1 method',car._car__var)

In [79]:
a=dog(40,50,60,100,200,600)

In [80]:
a._car__test()

this is the test method no help


In [87]:
dog._car__test1()

AttributeError: type object 'dog' has no attribute '_car__test1'

In [69]:
dog.test1(50)

this is the test1 method help


In [56]:
a.test1()

this is the test1 method help


In [159]:
#Filter out the integer value from this list
l=[['a','b','c'],[[4],1,2,'c']]
for i in range(len(l)):
    for j in range(len(l[i])):
        if type(l[i][j])==list:
            if type(l[i][j][0])==int:
                print(l[i][j][0])
        if type(l[i][j])==int:
            print(l[i][j])

4
1
2


In [20]:
class cat:
    _leg = 'cat leg'
    __eyes = 'cat eyes'
    nose = 'cat nose'
    
    def __init__(self,a,b,c):
        self.a=a
        self.b=b
        self.c=c
        
    def test1(self):
        return 'this is the test method of cat ',cat.__eyes
    def test2(self):
        return 'this is the test1 method of cat'
    
    


In [21]:
class dog(cat):
    _leg = 'dog leg'
    __eyes = 'dog eyes'
    nose = 'dog nose'
    
    def __init__(self,p,q,r,*args):
        self.p=p
        self.q=q
        self.r=r
        super(dog,self).__init__(*args)
        
    def test3(self):
        return 'this is the test method of dog',cat._leg
    
    def test4(self):
        return 'this is the test1 method of dog'
    

In [22]:
a=dog(2,56,5,65,85,90)

In [25]:
a.test3()

('this is the test method of dog', 'cat leg')

In [5]:
a._leg

'dog leg'

In [7]:
a._dog__eyes

'dog eyes'

In [15]:
a.nose

'dog nose'

In [18]:
a.test1()

'this is the test1 method of dog'

In [26]:
class person:
    _name = 'Zeeshan'
    __surname ='khan'
    yob =1996
    
    def _age(self,year):
        return year - person.yob
    
    def __age1(self,year1):
        return year1 -person.yob
class employee(person):
    _name = 'Zeeshan'
    __surname ='khan'
    yob =1996
    
    def _age2(self,year):
        return year - person.yob

    def __age3(self,year1):
        return year1 -person.yob

o=person()
print(o._person__age1(2022))
ob=employee()
print(ob._age(2022))
print(ob._person__age1(2022))
print(ob._age2(2022))
print(ob._employee__age3(2022))

26
26
26
26
26


In [17]:
# write a function to get the result as shown below
'''dict = {'a':[1, 2, 3], 'b':[1, 3, 5, 7], 'c':[4, 5, 6]} so that the output should be as below

{1: ['a', 'b'],
 2: ['a'],
 3: ['a', 'b'],
 5: ['b', 'c'],
 7: ['b'],
 4: ['c'],
 6: ['c']}'''

reverse_dict = {}
for key, value in dict.items():
    for i in value:
        reverse_dict.setdefault(i, list()).append(key)

In [18]:
reverse_dict

{1: ['a', 'b'],
 2: ['a'],
 3: ['a', 'b'],
 5: ['b', 'c'],
 7: ['b'],
 4: ['c'],
 6: ['c']}

In [2]:
#to insert the dataframe in Mysql workbench
import pandas as pd
import mysql.connector as cn
import seaborn as sn
df=sn.load_dataset('iris')
try:
    mydb=cn.connect(host='localhost',user='root',passwd='snzk@#1329')
    cursor=mydb.cursor()
    cursor.execute('create database test2000')
    cursor.execute('use test2000')
    cursor.execute('create table test(sepal_length varchar(1000), sepal_width varchar(1000), petal_length varchar(1000), petal_width varchar(1000),species varchar(1000))')
    mydb.commit()
except:
    mydb=cn.connect(host='localhost',user='root',passwd='snzk@#1329')
    cursor=mydb.cursor()
    cursor.execute('use test2000')
    for i,row in df.iterrows():
        cursor.execute('insert into test values (%s,%s,%s,%s,%s)',tuple(row))
    mydb.commit()
        

In [5]:
try:
    pd.read_csv('LUSID Excel - Manage Orders.xlsx')
    print('this is the correct approach')
except:
    print('something went wrong')

something went wrong


In [1]:
a=[[[[1,23,4,56,7]]]]
b=[[[[23,250,40,560,70]]]]

l=[]
q=[]
for i in a[0][0][0]:
    l.append(i)
for j in b[0][0][0]:
    q.append(j)
for m in l:
    for n in q:
        print(m-n,end=',')

-22,-249,-39,-559,-69,0,-227,-17,-537,-47,-19,-246,-36,-556,-66,33,-194,16,-504,-14,-16,-243,-33,-553,-63,

In [11]:
str1='faf'
str2='cat'
for i in str1:
    if i in str2:
        print('Can be possible')
        break
    else:
        print('cant')
        break
     

cant


In [13]:
z='zeeshan'
def test1(z):
    c={}
    for i in z:
        if i in c:
            c[i]+=1
        else:
            c[i]=1
    return c
    

In [14]:
test1('zeeshan')

{'z': 1, 'e': 2, 's': 1, 'h': 1, 'a': 1, 'n': 1}

In [15]:
z='zeeshan'
l=[]
for i in z:
    l.append(i)
l
for j in l:
    print(j,l.count(j))

z 1
e 2
e 2
s 1
h 1
a 1
n 1


In [17]:
while True:
    a = input()
    if a.isdigit():
        print('this is correct')
        break
    else:
        print('Enter the correct input')
    


dkfj
Enter the correct input
dlfkj
Enter the correct input
85
this is correct


In [4]:
while True:
    try:
        a = int(input())
        print('This is the correct input')
        break
    except:
        print('Enter the correct input')

    

dlk
Enter the correct input
ljj
Enter the correct input
lkj
Enter the correct input
0
This is the correct input


In [30]:
a='zeesha8 kdjflkd'
a.split('8')

['zeesha', ' kdjflkd']